### ISSUE TITLE
ZX3D50CE02S-USRC-4832 DMA is crashing

### ISSUE THREAD

**Issue by rightcornerengineering** [smartpanle/QMSD-ESP32-BSP#3]
When I tried to change the heap allocation to DMA, it got crash after uploading firmware.

#define QMSD_MALLOC_PSRAM(x)    heap_caps_malloc((x), MALLOC_CAP_SPIRAM | MALLOC_CAP_DMA)

**Comment by EeeeBin** [comment]
SPIRAM cannot be used for DMA

**Comment by rightcornerengineering** [comment]
> SPIRAM cannot be used for DMA

Why is it not available?

**Comment by EeeeBin** [comment]
Documentation：https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/mem_alloc.html#dma-capable-memory

**Comment by rightcornerengineering** [comment]
Closing this issue.
