### ISSUE TITLE
CONFIG_ESPTOOLPY_FLASHMODE="dio" gets added in sdkconfig automatically even though "CONFIG_ESPTOOLPY_FLASHMODE_QIO=y" has been configured in sdkconfig file 

### ISSUE THREAD

**Issue by pdckxd** [smartpanle/QMSD-ESP32-BSP#4]
Board: ZX7D00CE01S_8048
esp-idf version: 5.1 release
OS: Windows 10

`vim <path to>\QMSD-ESP32-BSP\example\get-start`

```
#
#Serial flasher config
#
#CONFIG_ESPTOOLPY_NO_STUB is not set
#CONFIG_ESPTOOLPY_OCT_FLASH is not set
CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT=y
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
#CONFIG_ESPTOOLPY_FLASHMODE_QOUT is not set
#CONFIG_ESPTOOLPY_FLASHMODE_DIO is not set
#CONFIG_ESPTOOLPY_FLASHMODE_DOUT is not set
CONFIG_ESPTOOLPY_FLASH_SAMPLE_MODE_STR=y
CONFIG_ESPTOOLPY_FLASHMODE="dio" #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< added by idf.py build automatically
#CONFIG_ESPTOOLPY_FLASHFREQ_120M is not set
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
```

`idf.py build`

```
... omit a lot of output...
Merged 2 ELF sections
Successfully created esp32s3 image.
Generated C:/Users/User/Documents/PlatformIO/Projects/QMSD-ESP32-BSP/example/get-start/build/get-start.bin
[1231/1231] cmd.exe /C "cd /D C:\Users\User\Documents\PlatformIO\Projects\QMSD-ESP32-BSP\example\get-start\build\esp-idf\esptool...tion_table/partition-table.bin C:/Users/User/Documents/PlatformIO/Projects/QMSD-ESP32-BSP/example/get-start/build/get-start.bin"get-start.bin binary size 0x6e300 bytes. Smallest app partition is 0x177000 bytes. 0x108d00 bytes (71%) free.

Project build complete. To flash, run this command:
C:\Espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe ..\..\..\..\..\..\esp-idf\components\esptool_py\esptool\esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32s3  write_flash --flash_mode dio --flash_size 16MB --flash_freq 80m 0x0 build\bootloader\bootloader.bin 0x8000 build\partition_table\partition-table.bin 0x10000 build\get-start.bin
```
if I replace --flash_mode dio to qio then call the flash command, I will get warning as below
`Warning: Image file at 0x0 is protected with a hash checksum, so not changing the flash mode setting. Use the --flash_mode=keep option instead of --flash_mode=qio in order to remove this warning, or use the --dont-append-digest option for the elf2image command in order to generate an image file without a hash checksum`

The question is how to flash the image with qio mode?

**Comment by EeeeBin** [comment]
This is the case in the idf sdkconfig generation rules. I don't know why this is the case. In fact, the flash mode configuration depends on CONFIG_ESPTOOLPY_FLASHMODE_QIO
![image](https://github.com/user-attachments/assets/20921e3e-19d5-4740-b250-6cf70f385748)

**Comment by pdckxd** [comment]
Thanks for quick response.
I found that finally the actual app runs at QIO mode even though firmware gets flashed with --flash_mode=dio. Closing
